### ISSUE TITLE
fetch_centromeres without information of centromeres

### ISSUE THREAD

**Issue by skytguuu** [open2c/bioframe#115]
Hi,

Recently, I tried to use fetch_centromeres to extract the mm9 centromeres data, however, the result showed nothing information of the centromeres of mm9. 

![image](https://user-images.githubusercontent.com/25957174/159220464-0333afe4-8467-4128-9c1e-c9b9f0fe3a8d.png)

It failed in mm9 or mm10, but it worked in hg38. 
Could you give me a hand? I don't know what is the problem ?

Thanks!
Garen

**Comment by agalitsyna** [comment]
Hi, @[skytguuu](https://github.com/skytguuu)! 

bioframe fetches the centromeres positions from `gap.txt` files of UCSC, and it does not list the centromeres for `mm9` because its chromosomes are telocentric (i.e. they are located at one end of each chromosome). That's why you have empty output with bioframe's fetch_centromeres as well. Basically, it means that there is a single chromosomal arm for each chromosome of mouse, and you do not need to split the chromosomes for Hi-C analysis. If you use bioframe.fetch_centromeres to set up the genomic view for cooltools analysis, then probably you do no need it for mouse! There are no chromosome arms of autosomes that might affect the analysis of compartments/scalings/etc. 

But if you are interested, there has been some controversy around formal definition of telomeres in mouse. For example, [`mm10` has centromeres at UCSC's gap.txt](https://www.biostars.org/p/445417/), but they are set to be the same. Also, chrY is not telocentric, but it's not usually used for the analysis nevertheless.

**Comment by skytguuu** [comment]
Hi, @agalitsyna ,

I have appreciated your clear explanation! Now, I have understood.

Thanks!

**Comment by gfudenberg** [comment]
I agree, great explanation!
I do wonder if it would be worth raising an error for mm9/mm10 & giving an
informative error message, perhaps linking to this issue

**Comment by agalitsyna** [comment]
@gfudenberg, I would rather output the warning if the centromeres positions aren't available. 

More importantly, but weirdly, UCSC sources are not equivalent here: https://github.com/open2c/bioframe/blob/e63c45a59e7d3e9f171e5b5462162d477d76e718/bioframe/io/resources.py#L139-L144 
The UCSC-based centromeres prioritize `client.fetch_centromeres`, and `mm10` centromeres are empty, but when you try to manually call the least prioritized option `client.fetch_gaps`, there is a valid output of telomere-centric centromeres, as they are listed in [mm10 gap.txt file](http://hgdownload.cse.ucsc.edu/goldenpath/mm10/database/gap.txt.gz). I don't understand why the UCSC fetchers have different behavior. It might be good to allow the user to select among these fetchers.

**Comment by gfudenberg** [comment]
Sounds good! Other suggestions @golobor or @nvictus ? Any broader centromere updates this might be good to wrap into?
