### ISSUE TITLE
docs rendering issues

### ISSUE THREAD

**Issue by gfudenberg** [open2c/bioframe#143]
extras not being displayed 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/19657573/231906068-25031a85-85b8-49f5-b838-11a6f00ba70c.png">

https://bioframe.readthedocs.io/en/latest/api-extras.html

**Comment by nvictus** [comment]
Based on the [log](https://readthedocs.org/api/v2/build/20058869.txt), the bbi import is failing, probably because we are [mocking out](https://github.com/open2c/bioframe/blob/main/docs/conf.py#L18) libraries like `numpy` in autodoc. We could probably mock out bbi as well, or instead decide not to mock anything.

**Comment by nvictus** [comment]
Works again.
