### ISSUE TITLE
in subtract(), add keep_order agrument

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#59]

**Comment by gfudenberg** [comment]
this should probably be added for cluster as well. 

I added this option for coverage but need to add a test for coverage(...., keep_order=True)

**Comment by gfudenberg** [comment]
this is now hard coded for subtract, since it involves an overlap with how='left'
![image](https://user-images.githubusercontent.com/19657573/129398209-1f3b706b-fd81-46fb-989e-6be0d4f1a01c.png)

cluster keeps order because of the set_index

complement creates new intervals, so keep_order is not relevant

cluster & complement are now similar to subtract
